version: "3.4"

services:
  authentication-service:
    image: "jahrim/io.github.jahrim.chess.authentication-service:${AUTHENTICATION_SERVICE_VERSION:-latest}"
    command:
      - --mongodb-connection
      - "${AUTHENTICATION_MONGODB_CONNECTION:?the authentication service won't be able to connect to MongoDB}"
      - --mongodb-database
      - "${AUTHENTICATION_MONGODB_DATABASE:-authentication}"
      - --mongodb-collection
      - "${AUTHENTICATION_MONGODB_COLLECTION:-users}"
      - --http-host
      - "0.0.0.0"
      - --http-port
      - "8080"
      - --allowed-origins
      - "${AUTHENTICATION_ALLOWED_ORIGINS:-*;}"
    ports:
      - "${HOSTNAME:-127.0.0.1}:${AUTHENTICATION_SERVICE_PORT:-8081}:8080"
    restart: always

  statistics-service:
    image: "jahrim/io.github.jahrim.chess.statistics-service:${STATISTICS_SERVICE_VERSION:-latest}"
    command:
      - --mongodb-connection
      - "${STATISTICS_MONGODB_CONNECTION:?the statistics service won't be able to connect to MongoDB}"
      - --mongodb-database
      - "${STATISTICS_MONGODB_DATABASE:-statistics}"
      - --mongodb-collection
      - "${STATISTICS_MONGODB_COLLECTION:-scores}"
      - --http-host
      - "0.0.0.0"
      - --http-port
      - "8080"
      - --allowed-origins
      - "${STATISTICS_ALLOWED_ORIGINS:-*;}"
    ports:
      - "${HOSTNAME:-127.0.0.1}:${STATISTICS_SERVICE_PORT:-8082}:8080"
    restart: always

  chess-game-service:
    depends_on:
      - statistics-service
    image: "jahrim/io.github.jahrim.chess.chess-game-service:${CHESS_GAME_SERVICE_VERSION:-latest}"
    command:
      - --statistics-service
      - "${HOSTNAME:-127.0.0.1}:${STATISTICS_SERVICE_PORT:-8082}"
      - --http-host
      - "0.0.0.0"
      - --http-port
      - "8080"
      - --allowed-origins
      - "${CHESS_GAME_SERVICE_ALLOWED_ORIGINS:-*;}"
    ports:
      - "${HOSTNAME:-127.0.0.1}:${CHESS_GAME_SERVICE_PORT:-8083}:8080"
    restart: always

  frontend:
    depends_on:
      - authentication-service
      - statistics-service
      - chess-game-service
    image: "jahrim/io.github.jahrim.chess.frontend:${FRONTEND_VERSION:-latest}"
    ports:
      - "${HOSTNAME:-127.0.0.1}:${FRONTEND_SERVICE_PORT:-8080}:8080"
    restart: always
    environment:
      VITE_RUNTIME_ENVIRONMENT: >
        {
          "AUTHENTICATION_SERVICE": "${HOSTNAME:-127.0.0.1}:${AUTHENTICATION_SERVICE_PORT:-8081}",
          "STATISTICS_SERVICE": "${HOSTNAME:-127.0.0.1}:${STATISTICS_SERVICE_PORT:-8082}",
          "CHESS_GAME_SERVICE": "${HOSTNAME:-127.0.0.1}:${CHESS_GAME_SERVICE_PORT:-8083}"
        }