version: "3.4"

services:
  authentication-service:
    image: "jahrim/io.github.jahrim.chess.authentication-service:${AUTHENTICATION_SERVICE_VERSION:-latest}"
    command:
      - --mongodb-connection
      - "${AUTHENTICATION_MONGODB_CONNECTION:?the authentication service won't be able to connect to MongoDB}"
      - --mongodb-database
      - "authentication"
      - --mongodb-collection
      - "users"
      - --http-host
      - "0.0.0.0"
      - --http-port
      - "8080"
    ports:
      - "${HOSTNAME:-127.0.0.1}:${AUTHENTICATION_SERVICE_PORT:-8081}:8080"
    restart: always

  statistics-service:
    image: "jahrim/io.github.jahrim.chess.statistics-service:${STATISTICS_SERVICE_VERSION:-latest}"
    command:
      - --mongodb-connection
      - "${STATISTICS_MONGODB_CONNECTION:?the statistics service won't be able to connect to MongoDB}"
      - --mongodb-database
      - "statistics"
      - --mongodb-collection
      - "scores"
      - --http-host
      - "0.0.0.0"
      - --http-port
      - "8080"
    ports:
      - "${HOSTNAME:-127.0.0.1}:${STATISTICS_SERVICE_PORT:-8082}:8080"
    restart: always

  # TODO de-comment when the chess game service will be published
  # chess-game-service:
  #   depends_on:
  #     - statistics-service
  #   image: "jahrim/io.github.jahrim.chess.chess-game-service:${CHESS_GAME_SERVICE_VERSION}:-latest"
  #   command:
  #     - --statistics-service
  #     - "${HOSTNAME:-127.0.0.1}:${STATISTICS_SERVICE_PORT:-8082}"
  #     - --http-host
  #     - "0.0.0.0"
  #     - --http-port
  #     - "8080"
  #   ports:
  #     - "${HOSTNAME:-127.0.0.1}:${CHESS_GAME_SERVICE_PORT:-8083}:8080"
  #   restart: always

  frontend:
    depends_on:
      - authentication-service
      - statistics-service
      # - chess-game-service TODO de-comment when the chess game service will be published
    image: "jahrim/io.github.jahrim.chess.frontend:${FRONTEND_VERSION:-latest}"
    ports:
      - "${HOSTNAME:-127.0.0.1}:${FRONTEND_SERVICE_PORT:-8080}:8080"
    restart: always
    environment:
      VITE_RUNTIME_ENVIRONMENT: >
        {
          "AUTHENTICATION_SERVICE": "${HOSTNAME:-127.0.0.1}:${AUTHENTICATION_SERVICE_PORT:-8081}",
          "STATISTICS_SERVICE": "${HOSTNAME:-127.0.0.1}:${STATISTICS_SERVICE_PORT:-8082}",
          "CHESS_GAME_SERVICE": "${HOSTNAME:-127.0.0.1}:${CHESS_GAME_SERVICE_PORT:-8083}",
        }